name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Build Debug APK (capture log)
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew --no-daemon assembleDebug --stacktrace --info > gradle-output.log 2>&1 || true
          else
            echo "gradlew not found - please commit Gradle wrapper files (gradlew, gradlew.bat, gradle/wrapper/*)"
            exit 1
          fi
          echo "==== tail of gradle-output.log ===="
          tail -n 200 gradle-output.log || true

      - name: Upload Gradle Log
        uses: actions/upload-artifact@v4
        with:
          name: gradle-log
          path: gradle-output.log

      - name: Ensure APK exists and rename (if present)
        run: |
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            mkdir -p artifacts
            cp "$APK_PATH" artifacts/GrblHAL-STM32-app-debug.apk
            echo "APK found and copied to artifacts/GrblHAL-STM32-app-debug.apk"
          else
            echo "APK not found at $APK_PATH"
          fi

      - name: Upload Debug APK (if present)
        uses: actions/upload-artifact@v4
        with:
          name: GrblHAL-STM32-APK
          path: artifacts/GrblHAL-STM32-app-debug.apk
          if-no-files-found: warn
