name: Build Android APK (grblHAL STM32 Support)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Make gradlew executable (if present)
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Build Debug APK
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew --no-daemon -Pandroid.injected.testOnly=false assembleDebug --stacktrace
          else
            echo "gradlew not found. Please add Gradle wrapper to the repo (gradlew, gradlew.bat, gradle/wrapper/*)."
            exit 1
          fi

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: GrblHAL-Android-STM32
          path: app/build/outputs/apk/debug/app-debug.apk
