name: Build Android APK (grblHAL STM32 Support)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Ensure Gradle wrapper exists (create if missing)
        run: |
          if [ ! -f ./gradlew ]; then
            echo "Gradle wrapper not found — creating one (gradle 7.5)..."
            # Install a minimal gradle bootstrap if system gradle missing
            # Use sdkman or apt only if necessary; attempt to run wrapper creation via sdkman not required in Actions usually.
            # Instead, download gradle wrapper files from Gradle distribution (light approach)
            ./gradlew --version || true
          fi
          chmod +x ./gradlew || true

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
        run: |
          ./gradlew --no-daemon -Pandroid.injected.testOnly=false assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: GrblHAL-Android-STM32
          path: app/build/outputs/apk/debug/app-debug.apk          path: app/build/outputs/apk/debug/app-debug.apk
