name: Extract ZIP on Push

on:
  push:
    paths:
      - "*.zip"

permissions:
  contents: write
  pull-requests: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Find and extract ZIP
        shell: bash
        run: |
          set -euo pipefail
          ZIPFILE=$(ls *.zip 2>/dev/null || true)
          if [ -z "$ZIPFILE" ]; then
            echo "No zip file found."
            exit 0
          fi
          mkdir -p extracted
          unzip -q "$ZIPFILE" -d extracted
          rm -f "$ZIPFILE"
          shopt -s dotglob
          cp -r extracted/* .
          shopt -u dotglob
          rm -rf extracted

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "Extracted ZIP automatically [skip ci]"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Extracted ZIP automatically [skip ci]"
          branch: extract-zip-${{ github.run_id }}
          title: "Auto-extract ZIP"
          body: "Auto-extracted ZIP from push"
          base: ${{ github.ref_name }}
